### ISSUE TITLE
results disappear on real IOS device after a short silence

### ISSUE THREAD

**Issue by Jankaz2** [jamsch/expo-speech-recognition#22] opened 2024-09-18 20:04 UTC
Hi, first of all thanks for this library, because it works much better than `react-native-voice`. Congratulations <3 

I have a small problem, because when I test it on the IOS emulator, it works perfectly. I can pause while speaking and everything is read correctly. However, on the real device, when I take a pause while speaking, then the results after the pause overwrite the results before the pause.

Here is my config
```typescript
//...
    const [settings, _] = useState<ExpoSpeechRecognitionOptions>({
        lang: languageToCode(lang! as Language) ?? 'en-NZ',
        interimResults: true,
        maxAlternatives: 3,
        continuous: true,
        requiresOnDeviceRecognition: false,
        addsPunctuation: true,
        androidIntentOptions: {
            EXTRA_SPEECH_INPUT_COMPLETE_SILENCE_LENGTH_MILLIS: 10000,
        },
    });


    useSpeechRecognitionEvent("result", (ev) => {
        const transcript = ev.results[0]?.transcript || "";

        setTranscription((current) => {
            const transcriptTally = ev.isFinal
                ? (current?.transcriptTally ?? "") + transcript
                : (current?.transcriptTally ?? "");

            return {
                transcriptTally,
                transcript: ev.isFinal ? transcriptTally : transcriptTally + transcript,
            };
        });
    });

    useSpeechRecognitionEvent("start", () => {
        setStatus("recognizing");
    });

    useSpeechRecognitionEvent("end", () => {
        setStatus("idle");
    });

    useSpeechRecognitionEvent("error", (ev) => {
        setError(ev);
        errorToast({title: `${t('toasts.somethingWentWrong')}`})
    });

    useSpeechRecognitionEvent("nomatch", (ev) => {
    });

     const startListening = () => {
        if (status !== "idle") return;

        setError(null);
        setStatus('starting');
        ExpoSpeechRecognitionModule.requestPermissionsAsync().then((result) => {
            if (!result.granted) {
                errorToast({title: t('toasts.permissionsNotGranted')})
                return;
            }
            ExpoSpeechRecognitionModule.start(settings);
        });
    };
```

And the videos presenting the problem

1. From emulator

https://github.com/user-attachments/assets/c2876b61-6904-4b0b-a66c-5949e8530f5b

2. The real device

https://github.com/user-attachments/assets/1adcd7a2-2cc4-41d4-927e-0951225d8ba6

**Comment by Jankaz2** [comment] 2024-09-18 21:08
I think it's the API problem instead of my code as I copied the example from this repo and problem is the same. 
Could you somehow increase the length of possible silence on IOS (I completely do not know swift) or maybe you can suggest some workaround? Would be really grateful

**Comment by jamsch** [comment] 2024-09-18 22:15
Hmm that's quite an unusual issue. The continuous mode on iOS doesn't have any special config around speech silence and under the hood we're only just setting some flags (such as `requiresOnDeviceRecognition`, `addsPunctuation`, `taskHint`, etc) for the underlying speech recognizer prior to starting. 

I haven't got an iOS device to test this out on right now but will get back to you in the next day or two. If I were to guess though, this may just have something to do with network-based recognition and you may want to enable `requiresOnDeviceRecognition` on iOS.

Could you provide me the following:

- A console.log() of the data from the start/result/end events on the physical device and paste them here
- The iOS version are you running on the physical device

Thanks!

**Comment by Jankaz2** [comment] 2024-09-19 05:42
I will send the logs in the next few hours, but for now I think the problem may be related to the IOS version. 
The first phone where the problem occurs has IOS 18.0 installed. But now I have tested the feature also on a phone with IOS 15 and it works fine. Also, I previously used the react-native-voice library with IOS 17.x.x and it also worked fine.
Maybe there are some changes in version 18.0?

**Comment by jamsch** [comment] 2024-09-19 06:01
@Jankaz2 Looks like you're right! https://forums.getdrafts.com/t/ios-18-macos-15-beta-warning-for-dictation-users/15334

>Apple has introduced a bug in their speech recognition frameworks that renders it impossible to do long-form dictation when running on iOS 18 or macOS 15. This will appear in Drafts as data being discarded as you dictate and only the most recent utterance being retained.

**Comment by Jankaz2** [comment] 2024-09-19 14:34
ok, so I guess we have to wait for the bugfixes from Apple. But the same problem is on Android emulator device (I do not have the real one to check), but maybe I am missing something in my speech config?

**Comment by Jankaz2** [comment] 2024-09-19 14:54
Ok, so I guess we just have to wait for bug fixes from Apple. 
But I have another question, because now I'm testing this on various Android emulators / real device, and the speech recognition stops right after I stop talking for a millisecond, even though I have an additional Android configuration of 
`EXTRA_SPEECH_INPUT_COMPLETE_SILENCE_LENGTH_MILLIS: 10000`. Am I missing something?

**Comment by jamsch** [comment] 2024-09-23 07:04
There's a hacky workaround that I'll be exploring to fix the iOS 18 issue that involves checking whether `speechDuration` is a positive number. It seems like the Apple engineers intended that this is a final result, so I'll be emitting a result event with `isFinal: true` here. That way, there shouldn't be any need for further changes on your end.

**Comment by jamsch** [comment] 2024-09-24 11:09
@Jankaz2 I've just released a new version at `expo-speech-recognition@0.2.20`. Let me know if that solves the issue for you.

**Comment by Jankaz2** [comment] 2024-09-24 15:44
yes, it works perfectly. thanks a lot :)

**Comment by jamsch** [comment] 2024-09-25 02:23
Sweet! Closing this issue. I might open up an issue for the Android <=12 continuous recording issue, but for the time being I've added a note to the README.

**Closed by jamsch** 2024-09-25 02:23 UTC

**Comment by liao02x** [comment] 2025-06-16 21:40
I can see this again from 1.1.1. Recognition is on device. Tested on the device and figured if you pause a bit longer, the result get started from scratch but there is no result with `"isFinal": true`. Confirmed this with an iphone 14 pro max with ios 17.1.1, an iphone 11 with ios 16.0. Also tested on iphone 12 with 17.6 and 18.5, couldn't repro. My guess is that this has something to do with the ios version. We are going to patch this from the js side, but this could be a problem in the native code

**Comment by liao02x** [comment] 2025-06-24 00:54
> Hey [@liao02x](https://github.com/liao02x), thank you for the insightful feedback! Next week I'll have time to test this on some iOS simulators to see if I can spot anything with iOS 17.1.1 and iOS 16.
> 
> If possible, could you post a log of the result events on one of the broken versions?

I tried on simulators (16.0) and it seems the issue would only present from device. I borrowed one device which has 16.0 and it's reproduced from it. I don't have the logs with me right now but I can share what is different from when it's working normally. 

My setup: lang: undefined, interimResults: true, continuous: true, requiresOnDeviceRecognition: true
The interim result would show up from the result event. It might look like
```
{
  "isFinal": false,
  "results": [
    {
      "transcript": "Hi",
      "confidence": 0 <- same 0 for all items
    },
    ...
  ]
}
```
And when the recognition is finished, there would be a final result which looks like this
```
{
  "isFinal": true,
  "results": [
    {
      "transcript": "Hi, this is a microphone test",
      "confidence": 0.9884645 <- different number for each item
    },
    ...
  ]
}
```

When the issue happens, the final result would still send the same result except that the isFinal would be false, so it would look like this
```
{
  "isFinal": false, <- this is wrong
  "results": [
    {
      "transcript": "Hi, this is a microphone test",
      "confidence": 0.9884645
    },
    ...
  ]
}
```

Since the rest of the results are still available, what I did from js side is to keep tracking the result events and manually patch the isFinal to be true if it detects the confidence change. This works from our side and hopefully could be helpful to anyone else who had this issue

**Comment by jamsch** [comment] 2025-06-24 01:12
@liao02x Hmm very strange,

- You probably won't see any `isFinal: true` while using continuous speech recognition on iOS <18 but if you `.stop()` is should process a final result and end.
  - But if you're seeing results wiping each other out (through new speech segments) because you can't concatenate previous results that's definitely an issue that needs to be fixed
- The `isFinal` attribute comes directly from the [SFSpeechRecognitionResult](https://developer.apple.com/documentation/speech/sfspeechrecognitionresult)
- The commit I did late last year at https://github.com/jamsch/expo-speech-recognition/commit/6e287e04f4767f8957ae960c345f5fd24a648df6 changes the `isFinal` value from `false` to `true` if it sees metadata for the speech, but only applies for iOS 18.0 because that's when Apple developer forum posts started popping up about this issue.

This may just need to be applied across the board for all iOS versions, however I'd have to look around on the Apple developer forums just to see if anyone else has anything similar to what you're having.

**Comment by liao02x** [comment] 2025-06-24 05:09
@jamsch actually the first device I tested on (ios 17.6.x) has this fully working (with isFinal: true), but also we have another device with ios 17.1.1 which has this issue. But we didn't see this from any ios 18 devices yet.
